-- Likes for artworks. Safe to run more than once.
create table if not exists public.artwork_likes (
  id bigint generated by default as identity primary key,
  artwork_id bigint not null references public.artworks(id) on delete cascade,
  voter_id text not null,
  created_at timestamptz not null default now(),
  constraint artwork_likes_one_vote_per_visitor unique (artwork_id, voter_id)
);

create index if not exists artwork_likes_artwork_id_idx
  on public.artwork_likes (artwork_id);

alter table public.artwork_likes enable row level security;

-- The site accesses this table only through its Vercel API using the service-role key.
