create table if not exists public.artworks (
  id bigint generated by default as identity primary key,
  title text not null,
  description text not null default '',
  image_path text not null,
  created_at timestamptz not null default now()
);

alter table public.artworks enable row level security;

drop policy if exists "Public can read artworks" on public.artworks;
create policy "Public can read artworks"
on public.artworks
for select
to anon, authenticated
using (true);

-- Upload/delete operations are performed by the Vercel API
-- using the Supabase service-role key, so no public write policy is needed.
