create table if not exists public.artwork_tickets (
  id bigint generated by default as identity primary key,
  title text not null,
  description text not null default '',
  image_path text not null,
  status text not null default 'pending' check (status in ('pending','approved','rejected')),
  created_at timestamptz not null default now(),
  reviewed_at timestamptz,
  artwork_id bigint references public.artworks(id) on delete set null
);
create index if not exists artwork_tickets_status_created_idx
  on public.artwork_tickets (status, created_at desc);
alter table public.artwork_tickets enable row level security;
